# Generated by Django 6.0 on 2025-12-18 22:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('resolution_km', models.FloatField()),
                ('grid_points_x', models.IntegerField()),
                ('grid_points_y', models.IntegerField()),
                ('center_lat', models.FloatField()),
                ('center_lon', models.FloatField()),
                ('min_lat', models.FloatField()),
                ('max_lat', models.FloatField()),
                ('min_lon', models.FloatField()),
                ('max_lon', models.FloatField()),
                ('file_suffix', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('unit', models.CharField(max_length=20)),
                ('grib_variable_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('color_scale', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ForecastRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateField()),
                ('run_time', models.TimeField()),
                ('initialization_time', models.DateTimeField()),
                ('forecast_hours', models.IntegerField(default=72)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fetching', 'Fetching Data'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('error_message', models.TextField(blank=True)),
                ('model_version', models.CharField(default='WRF-ARW v4.5', max_length=50)),
                ('physics_scheme', models.CharField(default='Thompson/RRTMG', max_length=100)),
                ('files_downloaded', models.JSONField(default=dict)),
                ('processing_log', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-run_date', '-run_time'],
                'indexes': [models.Index(fields=['-run_date', '-run_time'], name='wrf_data_fo_run_dat_78c3ba_idx'), models.Index(fields=['status'], name='wrf_data_fo_status_d531be_idx')],
                'unique_together': {('run_date', 'run_time')},
            },
        ),
        migrations.CreateModel(
            name='DataFetchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial Success'), ('failed', 'Failed')], max_length=20)),
                ('ssh_host', models.CharField(max_length=255)),
                ('ssh_user', models.CharField(max_length=100)),
                ('files_requested', models.IntegerField(default=0)),
                ('files_downloaded', models.IntegerField(default=0)),
                ('total_bytes', models.BigIntegerField(default=0)),
                ('log_messages', models.JSONField(default=list)),
                ('error_message', models.TextField(blank=True)),
                ('forecast_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fetch_logs', to='wrf_data.forecastrun')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ForecastData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_step', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('valid_time', models.DateTimeField()),
                ('grid_lats', models.JSONField()),
                ('grid_lons', models.JSONField()),
                ('values', models.JSONField()),
                ('color_data', models.JSONField()),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('mean_value', models.FloatField(blank=True, null=True)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrf_data.domain')),
                ('forecast_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='wrf_data.forecastrun')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrf_data.parameter')),
            ],
            options={
                'ordering': ['forecast_run', 'domain', 'parameter', 'time_step'],
                'indexes': [models.Index(fields=['forecast_run', 'domain', 'parameter', 'time_step'], name='wrf_data_fo_forecas_9b6718_idx'), models.Index(fields=['valid_time'], name='wrf_data_fo_valid_t_4d6351_idx')],
                'unique_together': {('forecast_run', 'domain', 'parameter', 'time_step')},
            },
        ),
    ]
